# Generated by Django 4.0.4 on 2022-05-20 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0002_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Customer',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_period_start', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=255)),
                ('current_period_end', models.DateField(auto_now_add=True)),
                ('cancel_at_period_end', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsapp.customer')),
            ],
        ),
    ]
