# Generated by Django 4.0.4 on 2022-05-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_rename_profile_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscribed',
        ),
        migrations.AlterField(
            model_name='order',
            name='current_period_end',
            field=models.DateField(),
        ),
    ]
